[general]
import = ["~/.config/alacritty/themes/themes/monokai_pro.toml"]

[terminal]
shell = { program = "/bin/zsh", args = ["-l"] }

[window]
blur = true
opacity = 0.8

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
size = 11

[keyboard]
bindings = [
    { key = "T", mods = "Super", mode = "~Vi", action = "CreateNewWindow" },
]

[mouse]
bindings = [
    { mouse = "Right", action = "Copy" },
    { mouse = "Middle", action = "Paste" },
]
