[general]
import = [
    "~/.config/alacritty/themes/themes/monokai_pro.toml"
]

[window]
blur = true
opacity = 1

[font]
normal = { family = "IosevkaTerm Nerd Font", style = "Regular" }
size = 11

[keyboard]
bindings = [
{ key = "T", mods = "Super", mode = "~Vi", action = "CreateNewWindow" },
]

[mouse]
bindings = [
{ mouse = "Right", action = "Copy" },
{ mouse = "Middle", action = "Paste" }
]
