# [general]
import = ["~/.config/alacritty/themes/themes/everforest_light.toml"]

[window]
# blur = true
opacity = 1

[font]
normal = { family = "Monaspace Neon", style = "Regular" }
bold = { family = "Monaspace Neon", style = "Bold" }
italic = { family = "Monaspace Neon", style = "Regular Italic" }
bold_italic = { family = "Monaspace Neon", style = "Bold Italic" }
size = 12


[keyboard]
bindings = [
    { key = "T", mods = "Super", mode = "~Vi", action = "CreateNewWindow" },
]

[mouse]
bindings = [
    { mouse = "Right", action = "Copy" },
    { mouse = "Middle", action = "Paste" },
]
